### ISSUE TITLE
Does not work under manjaro linux

### ISSUE THREAD

**Issue by frankspcmac** [andrew-ld/gameinput2xinput#3]
I cannot get this to work under manjaro linux wired or wireless. I am using a first gen ds5 controller. Tried with WINEDLLOVERRIDES="gameinput=n,b" %command%. still does nothing. Works fine under windows 11.

**Comment by andrew-ld** [comment]
hi, i am assuming you are talking about stalker 2.

have you verified that the same controller works with other games that use proton?

did you correctly copy the dll to “Stalker2/Binaries/Win64/gameinput.dll”?

in case both answers are positive send the gameinput.log file to this issue, it is generated in the same folder where you placed the dll.

**Comment by frankspcmac** [comment]
[gameinput.log](https://github.com/user-attachments/files/17997445/gameinput.log)

yes controller works fine in every other game.

yes the file is in the correct folder.

**Comment by andrew-ld** [comment]
[gameinput2xinput.dll.txt](https://github.com/user-attachments/files/17997633/gameinput2xinput.dll.txt)

resend logs with this dll, remove .txt because github dont allow upload dlls in the issue chat

changes: 4d8211e5b9f7d41b1a50ea357a40315d6d20d821

connect the controller before open the game, because i log some errors only the first time

**Comment by andrew-ld** [comment]
connect the controller before open the game, because i log some errors only the first time

**Comment by andrew-ld** [comment]
[gameinput2xinput.dll.txt](https://github.com/user-attachments/files/17997692/gameinput2xinput.dll.txt)

changes: c51366099e39116cd4018dccf8430e2772f404e7

**Comment by frankspcmac** [comment]
i had installed https://github.com/denilsonsa/udev-joystick-blacklist. problem is fixed after i uninstalled this. The reason for installing is i was trying to get ds4 controller working under manjaro.
