### ISSUE TITLE
Joycondrift with PowerA Controller

### ISSUE THREAD

**Issue by liberodark** [andrew-ld/gameinput2xinput#5]
Manjaro XFCE
Controller : `Bus 001 Device 007: ID 20d6:2009 PowerA Xbox Series X EnWired Controller Red inline`
Kernel : 6.6.63
[gameinput.log](https://github.com/user-attachments/files/18048338/gameinput.log)

**Comment by andrew-ld** [comment]
Elaborate more information

**Comment by liberodark** [comment]
Hi, 

Yes : 
After 2 or 3 seconds of inactivity in the game, the character moves sideways

Best Regards

**Comment by andrew-ld** [comment]
In what game and what kind of inactivity?

check if your controller is working properly, being a counterfeit controller it may not work properly (https://hardwaretester.com/gamepad).

**Comment by liberodark** [comment]
![image](https://github.com/user-attachments/assets/cb719e82-f30d-4cac-988f-9b5a1b9e5e66)

**Comment by andrew-ld** [comment]
the problem is your controller
