### ISSUE TITLE
STALKER 2 1.1.1 breaks controller support

### ISSUE THREAD

**Issue by heywoodlh** [andrew-ld/gameinput2xinput#8]
Obligatory issue that [STALKER 2's 1.1.1 patch](https://steamdb.info/patchnotes/16805297/) has seemingly broken the dll. :smile:

Might have some time this weekend to try and dedicate some time to learning how gameinput/xinput works and seeing if I can contribute a fix to this.

---

P.S. a developer guide/tutorial might make it easier for noobs like me to help contribute :smile:

**Comment by heywoodlh** [comment]
Interesting follow-up, it appears that the DLL is no longer necessary. After I re-enabled Steam Input, GameInput on Linux seems to be working on the latest update! :smile: Will close this issue.

**Comment by Howarddj** [comment]
Using a dualsense edge controller here, Steaminput is still broken for me and gameinput.dll is no longer working as of patch 1.1.2 in stalker 2.

hopefully this is an easy fix to get the dll working again for us dualsense users.
