### ISSUE TITLE
Stalker 2 patch 1.1.1 has broken gameinput again.

### ISSUE THREAD

**Issue by Howarddj** [andrew-ld/gameinput2xinput#9]
Running stalker 2 on Arch Linux via Proton Experimental, using a dualsense edge controller.

Everything worked perfectly until the recent round of game patches. Since updating to 1.1 and beyond i've lost controller support again even when using gameinput.dll.

There was a previous issue raised but quickly closed stating that steaminput was now working properly, though this doesn't seem to be the case for dualsense controllers. it is still broken for me using any sony controller.

Is this something that can be easily fixed to make the dll work again?

**Comment by andrew-ld** [comment]
could you send in this issue gameinput.log, it is located on the same folder where you put the dll

**Comment by Howarddj** [comment]
[gameinput.log](https://github.com/user-attachments/files/18245962/gameinput.log)

This is the log from the dll, it doesnt really show anything useful though. it seems like it should all be working as intended. 
i have read that the creator of specialK is having problems with stalker 2 aswell since the latest update. they have changed something in the game to do with directinput and xinput.

**Comment by andrew-ld** [comment]
are you using the latest dll?, if no update with latest release and resend logs

**Comment by Howarddj** [comment]
This log was pulled earlier this morning with the latest build in release. 

Edit: if it helps I'm using steam input to handle dualsense > Xbox emulation.

**Comment by andrew-ld** [comment]
the logs are interesting because it seems that it is not entering the condition for which the emulated controller is returned, now I make a new dll that logs more information to see why it is not entering that condition

**Comment by andrew-ld** [comment]
[gameinput2xinput.zip](https://github.com/user-attachments/files/18246538/gameinput2xinput.zip)


retry with this dll and send gameinput.log, it don't contains a fix is just for understand why doesn't works

**Comment by Howarddj** [comment]
[gameinput.log](https://github.com/user-attachments/files/18247721/gameinput.log)

new log file using new dll, hope it helps.

**Comment by andrew-ld** [comment]
[gameinput2xinput.zip](https://github.com/user-attachments/files/18251527/gameinput2xinput.zip)
maybe fix

**Comment by Howarddj** [comment]
yep that fixed it! dualsense edge all working again now using steam input.

awesome work!
